### PR TITLE
[김덕윤 240804] 알고리즘 문제 풀이

### PR DESCRIPTION
**Pull request by dukcode**
# 알고리즘 문제 풀이

완전탐색(brute force) 특집

- [algospot - CLOCKSYNC](https://algospot.com/judge/problem/stat/CLOCKSYNC/)
- [algospot - PICNIC](https://algospot.com/judge/problem/stat/PICNIC/)
- [algospot - BOGGLE](https://algospot.com/judge/problem/stat/BOGGLE/)
- [algospot - BOARDCOVER](https://algospot.com/judge/problem/stat/BOARDCOVER/)

### CODE REVIEW

**Review by JY-CH — APPROVED** [review]
👍 역시 대장 ㄷㄷ

**Review by Yachaeyong — APPROVED** [review]
👍

**Review by junpyo0920 — APPROVED** [review]
👍

**Review by sennaseo — APPROVED** [review]
👍

**Review by hohnmb — APPROVED** [review]
👍

**Pull request merged**
